name: Python Linting

# We want to do the linting when a Pull Request is opened, but also if it is updated. 
# TODO: Check whether the updated trigger actually works if a branch is updated or whether its 
# only for text. 

# We also only want to apply this rule if a Python file is updated. 
on: 
  pull_request:
    types: 
      [opened, edited]
    paths:  
      - '**.py'

# I think this job will need permissions to write to the branch as well. 
# Will test without this

permissions:
  contents: write

# On Ubuntu, we can use a use to pip install black and then somehow run it on the python file that was updated
jobs:
  lint_code: 
    name: Lint Code 
    runs-on: ubuntu-latest
    steps: 
      - name: Install Black
        run: |
          pip install black
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed Python files and Black them
        if: ${{ git diff --name-only -r HEAD^1 HEAD | grep *.py }}
        run: git diff --name-only -r HEAD^1 HEAD | grep *.py | black
      # - name: Commit the Changes to the Branch 
      #   run: 
        
    
